# Generated by Django 5.0.3 on 2024-04-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=50)),
            ],
        ),
    ]
