# Generated by Django 5.0.3 on 2024-04-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCS', '0002_sponsorship'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_checkout_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
    ]
