# Generated by Django 5.0.3 on 2024-04-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCS', '0007_alter_otpverification_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
