# Generated by Django 5.0.3 on 2024-04-22 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCS', '0009_customuser_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
