# Generated by Django 5.0.3 on 2024-05-26 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCS', '0014_contact_created_at_contact_polarity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('review', models.TextField()),
                ('sentiment_label', models.CharField(blank=True, max_length=20, null=True)),
                ('polarity', models.FloatField(blank=True, null=True)),
                ('subjectivity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
